name: i18n Check

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  i18n-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: i18n compile
        uses: ./.github/actions/build
        with:
          YARN_COMMAND: i18n
          USE_NEXT_CACHE: 'false'

      - name: check diff
        run: |
          if [[ -z $(git status -s) ]]
          then
            echo "i18n up to date"
          else
          	echo "please run yarn i18n"
            exit 1
          exit
          fi
